logging:
  level:
    org:
      zalando:
        logbook: TRACE
spring:
  sql:
    init:
      mode: always
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:h2:file:./db/filmorate
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
  h2:
    console:
      enabled: true